name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  objectbox: ^1.1.0
  objectbox_generator: ^1.1.0

dev_dependencies:
  build_runner: ^2.3.0
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0